export const RouteConstant = {
  login: "/auth/login",
  signup: "/auth/signup",
  forgetPwd: "/auth/forgot-password",
  resetPwd: "/auth/reset-password",
  contact: "/contact",
  programs: "/programs",
  alumni: "/alumni",
  about: "/about",
  faqs: "/faqs",
  apply: "/apply",
  dashboardApply: "/dashboard/apply",
  dashboardApplications: "/dashboard/applications",
  dashboard: "/dashboard",
  studentsform: "/form",
  assignments: "/dashboard/assignments",
  achievements: "/dashboard/achievements",
  studyGroups: "/dashboard/groups",
  schedule: "/dashboard/schedule",
  myCourses: "/dashboard/courses",
  overview: "/dashboard",
} as const;
