export const RouteConstant = {
  login: "/auth/login",
  signup: "/auth/signup",
  forgetPwd: "/auth/forgot-password",
  resetPwd: "/auth/reset-password",
  contact: "/contact",
  programs: "/programs",
  alumni: "/alumni",
  about: "/about",
  faqs: "/faqs",
  apply: "/dashboard/apply",
  dashboard: "/dashboard",
  dashboardApplications: "/dashboard/applications",
  dashboardPayments: "/dashboard/payments",
  dashboardNotifications: "/dashboard/notifications",
  studentsform: "/form",
  assignments: "/dashboard/assignments",
  certificates: "/dashboard/certificates",
  studyGroups: "/dashboard/groups",
  schedule: "/dashboard/schedule",
  myCourses: "/dashboard/courses",
  courseDetails: "/dashboard/courses/:courseId",
  overview: "/dashboard",
  settings: "/dashboard/settings",
  adminDashboard: "/admin/dashboard",
} as const;
